site_name: muniverse-decomposition

theme:
  name: mkdocs
  nav_style: primary
  hljs_style: github-dark
  hljs_style_dark: github-dark
  user_color_mode_toggle: true
  titles_only: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            members_order: source
            show_root_heading: true    
            inherited_members: true    

nav:
  - Home: index.html
  - Tutorials:
    - Installation: tutorials/install.md
    - Pre-Processing: tutorials/todo.ipynb
  - API Reference: 
    - BIDS-EMG: api/bids.md
    - Pre-Processing: api/pre_processing.md
    - Algorithms: api/algorithms.md
 
    
    