# ae_decomposer.py
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
# Reuse your existing utilities (same package structure as your CBSS snippet)
from .core import (
    bandpass_signals,
    notch_signals,
    extension,
    whitening,
    est_spike_times,
    # remove_duplicates,
    # remove_bad_sources,
    peel_off,
)

# ----------------------------
#   Building blocks
# ----------------------------

class _OrthogonalEncoderSO(nn.Module):
    """
    Orthogonally constrained linear map V \in SO(Din), then we take the
    first Dout rows to get a rectangular encoder W = V[:Dout, :].

    Forward: y = W @ x, where x: [B, Din] (time-batch), y: [B, Dout].
    """
    def __init__(
            self, 
            din: int, 
            dout: int, 
            init_scale: float = 1e-3, 
            device="cpu", 
            dtype=torch.float32
    ):
        super().__init__()
        assert dout <= din, "dout must be <= din (take first rows of SO(din))."
        self.din = din
        self.dout = dout
        self.register_parameter(
            "A",
            nn.Parameter(init_scale * torch.randn(din, din, device=device, dtype=dtype))
        )

    def forward(
            self, 
            x: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        TODO Add Docstring
        
        """
        # Skew-symmetric parameter -> Lie algebra so(n)
        # K = A - A^T, then V = expm(K) \in SO(n)
        K = self.A - self.A.transpose(-1, -2)
        V = torch.matrix_exp(K)  # [din, din], guaranteed orthogonal with det=+1 if initialized near 0
        W = V[: self.dout, :]    # take first rows -> rectangular
        y = x @ W.t()            # x: [B, din] -> y: [B, dout]
        return y, W  # return W so we can export filters later


class _TanhshrinkLayer(nn.Module):
    def forward(self, x):
        return x - torch.tanh(x)


class _EMGAutoencoder(nn.Module):
    """
    Class implementing an autoencoder to model time series
    data X generated by some latent sources s

    Properties
    ----------
        din : int
            Dimension of TODO
        dlat : int
            Dimension of the latent variable describing the data
        device : str
            TODO
        dtype : TODO
            TODO            

    Attributes
    ---------- 
        encoder : nn.Module
            TODO
        relu : nn.Module
            TODO
        decoder : nn.Module
            TODO  
        tanhshrink : nn.Module
            TODO       


    Encoder: y = ReLU( W x ), with W orthogonal rows from SO(Din)
    Decoder: x_hat = Tanhshrink( y @ Z^T + b ), fully unconstrained
    """
    def __init__(
            self, 
            din: int, 
            dlat: int, 
            device="cpu", 
            dtype=torch.float32
    ):

        super().__init__()
        if isinstance(dtype, str):
            dtype = getattr(torch, dtype)
        self.encoder = _OrthogonalEncoderSO(
            din, dlat, device=device, dtype=dtype
        )
        self.relu = nn.ReLU(inplace=False)
        self.decoder = nn.Linear(
            dlat, din, bias=True, device=device, dtype=dtype
        )
        self.tanhshrink = _TanhshrinkLayer()

        # Xavier init for decoder
        nn.init.xavier_uniform_(self.decoder.weight)
        nn.init.zeros_(self.decoder.bias)

    def forward(self, x):
        """
        x: [B, Din]
        returns: x_hat [B, Din], s_hat [B, dlat], W [dlat, Din]
        """
        y_lin, W = self.encoder(x)      # [B, dlat], [dlat, Din]
        s_hat = self.relu(y_lin)        # nonnegative sparse spikes
        x_lin = self.decoder(s_hat)     # [B, Din]
        x_hat = self.tanhshrink(x_lin)  # denoise tiny values

        return x_hat, s_hat, W



# ----------------------------
#   Main API (mirrors CBSS)
# ----------------------------

class AEDecoderConfig:
    def __init__(self, **kwargs):
        # Preprocessing
        self.bandpass = [20, 500]
        self.bandpass_order = 2
        self.notch_frequency = 50
        self.notch_n_harmonics = 3
        self.notch_order = 2
        self.notch_width = 1

        # Temporal extension
        self.ext_fact = 2  # R (paper found R=2 best)
        # Whitening
        self.whitening_method = "ZCA"
        self.whitening_reg = "auto"

        # Model dims
        self.latent_dim = None  # default -> number of original channels m

        # Training
        self.epochs = 100
        self.batch_size = 5000         # samples per batch (time-slices)
        self.learning_rate = 8e-3
        self.sparsity_p = 0.9
        self.sparsity_q = 1.8
        self.lambda_sparsity = 1.0
        self.weight_decay = 0.0
        self.device = "cpu"
        self.dtype = torch.float32
        self.random_seed = 1909
        self.shuffle_windows = True

        # Post-processing / evaluation
        self.cluster_method = "kmeans"
        self.sil_th = 0.9
        self.cov_th = 0.30
        self.min_num_spikes = 10
        self.match_th = 0.3
        self.match_max_shift = 0.1
        self.match_tol = 0.001

        # Optional iterative peeling (like CBSS)
        self.enable_peel_off = True
        self.peel_win = 0.025

        for k, v in kwargs.items():
            setattr(self, k, v)


class AEDecoder:
    """
    Class implementing autoencoder-based EMG (unsupervised) decomposition 

    Properties
    ----------
        ext_fact : int, default 2
            Number of delayed copies
        ...    

        epochs : int , default 100
            TODO Describe
        batch_size : int , default 5000         
            Number of time samples per batch
        learning_rate : float , default 8e-3
            Learning rate used to train the autoencoder
        sparsity_p : float, default 0.9
            TODO
        sparsity_q : float , default 1.8
            TODO Describe
        lambda_sparsity : float , default 1.0
            TODO Describe
        weight_decay : float, default 0.0
            TODO Describe
        device : str , default "cpu" TODO Add valid options
            TODO Describe
        dtype : TODO , default torch.float32 TODO Add valid options
            TODO Describe
        random_seed : int , default 1909
            TODO Describe
        shuffle_windows : bool , default True
            TODO Describe


    Attributes
    ----------
        autoencoder_ : nn.Module
            Class for the data model 

    
    References
    ----------
    .. [1] Mayer et al. (2023).


    Examples
    --------
    TODO Showcase API

    """
    def __init__(
            self, 
            config: AEDecoderConfig | None = None, **kwargs
    ):
        
        self.cfg = config if config is not None else AEDecoderConfig()
        for k, v in kwargs.items():
            setattr(self.cfg, k, v)

        # For reproducibility
        torch.manual_seed(self.cfg.random_seed)
        np.random.seed(self.cfg.random_seed)

    def _to_torch(self, x: np.ndarray) -> torch.Tensor:
        """Convert numpy array to PyTorch object"""

        if isinstance(self.cfg.device, str):
            device = torch.device(self.cfg.device) 
        else:
            device = self.cfg.device

        if isinstance(self.cfg.dtype, str):
            dtype = getattr(torch, self.cfg.dtype)
        else:
            dtype = self.cfg.dtype
        return torch.from_numpy(x).to(device=device, dtype=dtype)

    def _prep_signal(self, sig: np.ndarray, fsamp: float):
        """
        Preprocess:
          - bandpass / notch
          - temporal extension
          - mean removal & edge zeroing like CBSS
          - whitening (returns whitened signal and whitening matrix Z)
        """
        # Bandpass
        # if self.cfg.bandpass is not None:
        #     sig = bandpass_signals(
        #         sig, fsamp,
        #         high_pass=self.cfg.bandpass[0],
        #         low_pass=self.cfg.bandpass[1],
        #         order=self.cfg.bandpass_order
        #     )
        # # Notch
        # if self.cfg.notch_frequency is not None:
        #     sig = notch_signals(
        #         sig, fsamp,
        #         nfreq=self.cfg.notch_frequency,
        #         dfreq=self.cfg.notch_width,
        #         order=self.cfg.notch_order,
        #         n_harmonics=self.cfg.notch_n_harmonics,
        #     )

        # Temporal extension
        ext_sig = extension(sig, self.cfg.ext_fact)  # [m*R, T]
        ext_sig = ext_sig - np.mean(ext_sig, axis=1, keepdims=True)

        # edge zeroing (like CBSS)
        cut = self.cfg.ext_fact * 2
        ext_sig[:, :cut] = 0
        ext_sig[:, -cut:] = 0

        # Whitening
        white_sig, Z, Zinv = whitening(
            Y=ext_sig,
            method=self.cfg.whitening_method,
            backend="svd",
            regularization=self.cfg.whitening_reg,
        )
        return white_sig, Z  # shapes: [mR, T], [mR, mR]

    def _iter_minibatches(self, Xw: torch.Tensor):
        """ 
        Yield batched [B, Din] slices from Xw.T (Din = mR).
        Xw: [Din, T] torch tensor
        
        """
        T = Xw.shape[0]

        if self.cfg.shuffle_windows:
            idx = torch.randperm(T, device=Xw.device)
        else:
            idx = torch.arange(T, device=Xw.device)

        for start in range(0, T, self.cfg.batch_size):
            sel = idx[start:start + self.cfg.batch_size]
            yield Xw[sel]  # already [B, Din]        

    def _build_model(
            self, 
            din: int, 
            m_orig: int
    ):
        """Set up autoencoder model"""

        if self.cfg.latent_dim is not None:
            dlat = self.cfg.latent_dim
        else:
            dlat = m_orig

        self.autoencoder_ = _EMGAutoencoder(
            din=din,
            dlat=dlat,
            device=self.cfg.device,
            dtype=self.cfg.dtype
        )
        # Convert device to proper PyTorch object
        if isinstance(self.cfg.device, str):
            device = torch.device(self.cfg.device) 
        else:
            device = self.cfg.device

        self.autoencoder_.to(device)    

    def _train_autoencoder(self, Xw: torch.tensor):
        """
        Train the Autoencoder model given some training data

        Args
        ----
            Xw : torch.tensor
                Whitened data 
        
        
        """

        # Set up optimizer
        optim = torch.optim.Adam(
            self.autoencoder_.parameters(),
            lr=self.cfg.learning_rate,
            weight_decay=self.cfg.weight_decay
        )
        self.autoencoder_.train()

        # Loop ober data batches
        for epoch in range(self.cfg.epochs):
            epoch_loss = 0.0
            nb = 0
            for xb in self._iter_minibatches(Xw):
                # Reset optimizer
                optim.zero_grad()
                # Estimate data
                x_hat, s_hat, _ = self.autoencoder_(xb)
                # Compute the reconstruction error
                rec = F.mse_loss(x_hat, xb)
                # Compute the sparsity penalty
                sp = self._lp_lq_sparsity(
                    s_hat, p=self.cfg.sparsity_p, q=self.cfg.sparsity_q
                )
                # Compute total loss and do optimization step
                loss = rec + self.cfg.lambda_sparsity * sp
                loss.backward()
                optim.step()

                epoch_loss += loss.item()
                nb += 1
            # (Optional) print training progress
            # print(f"[AE] epoch {epoch+1}/{self.cfg.epochs}  loss={epoch_loss/max(1,nb):.5f}")

    def _postprocess(
            self, 
            sources: np.ndarray, 
            fsamp: float
            #Xw: np.ndarray
    ):
        """ Spike detection and source quality estimation"""
        n_mu = sources.shape[0]
        spikes = {i: [] for i in range(n_mu)}
        sil = np.zeros(n_mu)

        # Spike detection on each latent 
        for i in range(n_mu):
            spikes[i], sil[i] = est_spike_times(
                sources[i, :], fsamp
            )

        # NOTE The output of the peel off seems to be never used
        # # Optional peel-off in whitened domain (helps reduce overlap influence)
        # if self.cfg.enable_peel_off:
        #     Xw_res = Xw.copy()
        #     for i in range(n_mu):
        #         if len(spikes[i]) == 0:
        #             continue
        #         # peel_off expects channels x time; Xw_res is [Din, T] already
        #         Xw_res, _, _ = peel_off(
        #             Xw_res, spikes[i],
        #             win=self.cfg.peel_win,
        #             fsamp=fsamp
        #         )


        return spikes, sil
    
    def _lp_lq_sparsity(
            self, 
            s_hat: torch.Tensor, 
            p=0.9, 
            q=1.8, 
            eps=1e-8
    ):
        """
        Temporal sparsity penalty: log10( (q/p) * ||s||_p / ||s||_q ), averaged over units.
        s_hat: [B, dlat]
        We compute norms over time within a window; aggregate across batch as mean.
        """
        # Sum across batch -> a time-aggregated view for this mini-batch
        # (treat batch as temporal slices)
        ss = torch.clamp(s_hat, min=0.0)  # already ReLU but be safe
        # Compute norms per-unit across batch
        # Avoid zero by eps to keep gradient stable
        lp = torch.pow(torch.sum(
            torch.pow(ss + eps, p), dim=0) + eps, 1.0 / p
        )   # [dlat]
        lq = torch.pow(torch.sum(
            torch.pow(ss + eps, q), dim=0) + eps, 1.0 / q
        )   # [dlat]
        ratio = (q / p) * (lp / (lq + eps))
        penalty = torch.log10(ratio + eps).mean()

        return penalty

    def fit_predict(
            self, 
            sig: np.ndarray, 
            fsamp: float
    ):
        """
        Args
        ----
            sig : np.ndarray 
                EMG data (n_channels, n_samples)
            fsamp: float 
                sampling frequency (Hz)

        Returns
        -------
            sources : ndarray 
                Estimated latents respresenting sources (n_mu x n_samples)
            spikes : dict 
                Sample indices of motor neuron discharges
            sil : np.ndarray 
                Silhouette-like scores per source
            mu_filters : np.ndarray 
                Encoder filters over whitened-extended space (dlat, mR)
        """
        # ---- Preprocess (extension + whitening) ----
        Xw, Z = self._prep_signal(sig, fsamp)  # [mR, T], [mR, mR]
        mR, T = Xw.shape
        m = sig.shape[0]
        Din = mR

        Xw_torch = self._to_torch(Xw)

        # ---- Build & train AE ----
        self._build_model(din=Din, m_orig=m)
        self._train_autoencoder(Xw_torch.T)

        # ---- Infer latent sources across full sequence ----
        with torch.no_grad():
            x_hat, s_hat, W = self.autoencoder_(Xw_torch.T)

        sources = s_hat.transpose(0, 1).cpu().numpy()  # [dlat, T]
        mu_filters = W.detach().cpu().numpy().T     

        # ---- Postprocess (spikes, duplicates, pruning) ----
        spikes, sil = self._postprocess(sources, fsamp)

        # Match output signature of CBSS
        # sources must be (n_mu x n_samples). Our latent 'sources' are over [T]; we already have that.
        return sources, spikes, sil, mu_filters
