# ae_decomposer.py
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Literal, List, Union, Annotated
# Reuse your existing utilities (same package structure as your CBSS snippet)
from .core import (
    bandpass_signals,
    notch_signals,
    extension,
    whitening,
    est_spike_times,
    spike_dict_to_long_df,
    # remove_duplicates,
    # remove_bad_sources,
    peel_off,
)

# ----------------------------
#   Building blocks
# ----------------------------

class _OrthogonalEncoderSO(nn.Module):
    """
    Orthogonally constrained linear map V \in SO(Din), then we take the
    first Dout rows to get a rectangular encoder W = V[:Dout, :].

    Forward: y = W @ x, where x: [B, Din] (time-batch), y: [B, Dout].
    """
    def __init__(
            self, 
            din: int, 
            dout: int, 
            init_scale: float = 1e-3, 
            device="cpu", 
            dtype=torch.float32
    ):
        super().__init__()
        assert dout <= din, "dout must be <= din (take first rows of SO(din))."
        self.din = din
        self.dout = dout
        self.register_parameter(
            "A",
            nn.Parameter(init_scale * torch.randn(din, din, device=device, dtype=dtype))
        )

    def forward(
            self, 
            x: torch.Tensor
    ) -> torch.Tensor:
        """
        TODO Add Docstring
        
        """
        # Skew-symmetric parameter -> Lie algebra so(n)
        # K = A - A^T, then V = expm(K) \in SO(n)
        K = self.A - self.A.transpose(-1, -2)
        V = torch.matrix_exp(K)  # [din, din], guaranteed orthogonal with det=+1 if initialized near 0
        W = V[: self.dout, :]    # take first rows -> rectangular
        y = x @ W.t()            # x: [B, din] -> y: [B, dout]
        return y
    
    @property
    def W(self):
        """Extract W for inspection"""
        K = self.A - self.A.T
        V = torch.matrix_exp(K)
        return V[:self.dout, :]


class _TanhshrinkLayer(nn.Module):
    def forward(self, x):
        return x - torch.tanh(x)


class _EMGAutoencoder(nn.Module):
    """
    Class implementing an autoencoder to model time series
    data X generated by some latent sources s

    Properties
    ----------
        din : int
            Dimension of TODO
        dlat : int
            Dimension of the latent variable describing the data
        device : str
            TODO
        dtype : TODO
            TODO            

    Attributes
    ---------- 
        encoder : nn.Module
            TODO
        relu : nn.Module
            TODO
        decoder : nn.Module
            TODO  
        tanhshrink : nn.Module
            TODO       


    Encoder: y = ReLU( W x ), with W orthogonal rows from SO(Din)
    Decoder: x_hat = Tanhshrink( y @ Z^T + b ), fully unconstrained
    """
    def __init__(
            self, 
            din: int, 
            dlat: int, 
            device="cpu", 
            dtype=torch.float32
    ):

        super().__init__()
        if isinstance(dtype, str):
            dtype = getattr(torch, dtype)
        self.encoder = _OrthogonalEncoderSO(
            din, dlat, device=device, dtype=dtype
        )
        self.relu = nn.ReLU(inplace=False)
        self.decoder = nn.Linear(
            dlat, din, bias=True, device=device, dtype=dtype
        )
        self.tanhshrink = _TanhshrinkLayer()

        # Xavier init for decoder
        nn.init.xavier_uniform_(self.decoder.weight)
        nn.init.zeros_(self.decoder.bias)

    def forward(self, x):
        """
        x: [B, Din]
        returns: x_hat [B, Din], s_hat [B, dlat], W [dlat, Din]
        """
        y_lin = self.encoder(x)      # [B, dlat], [dlat, Din]
        s_hat = self.relu(y_lin)        # nonnegative sparse spikes
        x_lin = self.decoder(s_hat)     # [B, Din]
        x_hat = self.tanhshrink(x_lin)  # denoise tiny values

        return x_hat, s_hat

class AEDecoder:
    """
    Class implementing autoencoder-based EMG (unsupervised) decomposition 

    Properties
    ----------
        ext_fact : int, default 2
            Number of delayed copies
        ...    

        latent_dim : int or None , default None
            Dimensionality of the latent sources. If None the number
            of EMG channels is used
        epochs : int , default 100
            TODO Describe
        batch_size : int , default 5000         
            Number of time samples per batch
        learning_rate : float , default 8e-3
            Learning rate used to train the autoencoder
        sparsity_p : float, default 0.9
            TODO
        sparsity_q : float , default 1.8
            TODO Describe
        lambda_sparsity : float , default 1.0
            TODO Describe
        weight_decay : float, default 0.0
            TODO Describe
        device : str or torch.device , default "cpu" 
            TODO Describe
        dtype : torch.dtype , default torch.float32 
            TODO Describe
        random_seed : int , default 1909
            TODO Describe
        shuffle_windows : bool , default True
            TODO Describe


    Attributes
    ----------
        autoencoder_ : nn.Module
            Class with the data model 
        whiten_ : np.ndarray
            The whitening matrix
        unwhiten_ : np.ndarray
            The unwhietning matrix  
        TODO Add some markers on algorithm progress      

    
    References
    ----------
    .. [1] Mayer et al. (2023).


    Examples
    --------
    TODO Showcase API

    """
    def __init__(
            self,
            spike_detection_exp: float = 2,
            spike_detection_min_delay: float = 0.01,
            ext_fact: int = 2, # R (paper found R=2 best)
            whitening_method: Literal["ZCA", "PCA", "Cholesky"] =  "ZCA", 
            whitening_backend: Literal["ed", "svd"] = "svd",
            whitening_reg = "auto", 
            latent_dim: int | None = None,
            epochs: int = 100,
            batch_size: int = 5000 ,
            learning_rate: float = 8e-3,
            sparsity_p: float = 0.9,
            sparsity_q: float = 1.8,
            sparsity_eps: float = 1e-8,
            lambda_sparsity: float = 1.0,
            weight_decay: float = 0.0,
            device: torch.device | str = "cpu", 
            dtype: torch.dtype | str = "float32", 
            random_seed: int = 1909, 
            shuffle_windows: bool = True,
            verbose: bool = False,
            config: dict | None = None, 
            #config: AEDecoderConfig | None = None, **kwargs
    ):
        
        self.ext_fact = ext_fact
        # Whitening
        self.whitening_method = whitening_method
        self.whitening_reg = whitening_reg
        self.whitening_backend = whitening_backend

        # Spike clustering
        self.spike_detection_exp = spike_detection_exp
        self.spike_detection_min_delay = spike_detection_min_delay

        # Model dims
        self.latent_dim = latent_dim  # default -> number of original channels m

        # Training
        self.epochs = epochs
        self.batch_size = batch_size         # samples per batch (time-slices)
        self.learning_rate = learning_rate
        self.sparsity_p = sparsity_p
        self.sparsity_q = sparsity_q
        self.sparsity_eps = sparsity_eps
        self.lambda_sparsity = lambda_sparsity
        self.weight_decay = weight_decay
        self.random_seed = random_seed
        self.shuffle_windows = shuffle_windows

        self.verbose = verbose

        if isinstance(device, str):
            self.device = torch.device(device) 
        else:
            device = device
        if isinstance(dtype, str):
            self.dtype = getattr(torch, dtype)
        else:
            self.dtype = dtype

        # For reproducibility
        torch.manual_seed(self.random_seed)
        np.random.seed(self.random_seed)

        # Convert config object (if provided) to a dictionary
        config_dict = vars(config) if config is not None else {}

        valid_keys = self.__dict__.keys()

        # Assign all parameters as attributes
        for key, value in config_dict.items():
            if key in valid_keys:
                setattr(self, key, value)
            else:
                print(f"Warning: ignoring invalid parameter: {key}")

    def _to_torch(self, x: np.ndarray) -> torch.Tensor:
        """Convert numpy array to PyTorch object"""

        if isinstance(self.device, str):
            device = torch.device(self.device) 
        else:
            device = self.device

        if isinstance(self.dtype, str):
            dtype = getattr(torch, self.dtype)
        else:
            dtype = self.dtype
        return torch.from_numpy(x).to(device=device, dtype=dtype)

    def _extension(self, sig: np.ndarray):
        """Extend and whiten the data matrix"""

        # Temporal extension
        ext_sig = extension(sig, self.ext_fact)  # [m*R, T]
        ext_sig = ext_sig - np.mean(ext_sig, axis=1, keepdims=True)

        # Remove edges 
        cut = self.ext_fact * 2
        ext_sig[:, :cut] = 0
        ext_sig[:, -cut:] = 0

        return ext_sig # (n_features, n_samples)
    
    def _whitening(self, ext_sig: np.ndarray):

        # Whitening
        white_sig, self.white_, self.unwhite_ = whitening(
            Y=ext_sig,
            method=self.whitening_method,
            backend=self.whitening_backend,
            regularization=self.whitening_reg,
        )
        return white_sig # (n_features, n_samples)

    def _iter_minibatches(self, Xw: torch.Tensor):
        """ 
        Yield batched [B, Din] slices from Xw.T (Din = mR).
        Xw: [Din, T] torch tensor
        
        """
        T = Xw.shape[0]

        if self.shuffle_windows:
            idx = torch.randperm(T, device=Xw.device)
        else:
            idx = torch.arange(T, device=Xw.device)

        for start in range(0, T, self.batch_size):
            sel = idx[start:start + self.batch_size]
            yield Xw[sel]  # already [B, Din]        

    def _init_autoencoder(
            self, 
            n_features: int, 
            n_emg_ch: int
    ):
        """
        Initalize the autoencoder model

        Args
        ----
            n_features : int
                Number features of the whitened data matrix
            n_emg_ch : int
                Number of EMG channels. Is used as the dimension
                of the latent space if no value is provided    

        """

        if self.latent_dim is not None:
            n_latents = self.latent_dim
        else:
            n_latents = n_emg_ch

        self.autoencoder_ = _EMGAutoencoder(
            din=n_features,
            dlat=n_latents,
            device=self.device,
            dtype=self.dtype
        )
        # Convert device to proper PyTorch object
        if isinstance(self.device, str):
            device = torch.device(self.device) 
        else:
            device = self.device

        self.autoencoder_.to(device)    

    def _train_autoencoder(self, Xw: torch.Tensor):
        """
        Train the Autoencoder model given training data Xw

        Args
        ----
            Xw : torch.Tensor
                Whitened data 
        
        
        """

        # Set up optimizer
        optim = torch.optim.Adam(
            self.autoencoder_.parameters(),
            lr=self.learning_rate,
            weight_decay=self.weight_decay
        )
        self.autoencoder_.train()

        # Loop ober data batches
        for epoch in range(self.epochs):
            epoch_loss = 0.0
            nb = 0
            for xb in self._iter_minibatches(Xw):
                # Reset optimizer
                optim.zero_grad()
                # Estimate data
                x_hat, s_hat = self.autoencoder_(xb)
                # Compute the reconstruction error
                rec = F.mse_loss(x_hat, xb)
                # Compute the sparsity penalty
                sp = self._lp_lq_sparsity(s_hat)
                # Compute total loss and do optimization step
                loss = rec + self.lambda_sparsity * sp
                loss.backward()
                optim.step()

                epoch_loss += loss.item()
                nb += 1
            # (Optional) print training progress
            # print(f"[AE] epoch {epoch+1}/{self.cfg.epochs}  loss={epoch_loss/max(1,nb):.5f}")

    def _postprocess(
            self, 
            sources: np.ndarray, 
            fsamp: float
            #Xw: np.ndarray
    ):
        """ Spike detection and source quality estimation"""
        n_mu = sources.shape[0]
        spikes = {i: [] for i in range(n_mu)}

        scores = {
            "sil": np.zeros(n_mu),
            "cov_isi": np.zeros(n_mu),
        }

        

        # Spike detection on each latent 
        for i in range(n_mu):
            spikes[i], scores["sil"][i] = est_spike_times(
                source=sources[i, :], 
                fsamp=fsamp, 
                a=self.spike_detection_exp, 
                min_delay=self.spike_detection_min_delay
            )

            if len(spikes[i]) > 2:
                isi = np.diff(spikes[i] / fsamp)
                scores["cov_isi"][i] = np.std(isi) / np.mean(isi)
            else:
                scores["cov_isi"][i] = np.inf

        # NOTE The output of the peel off seems to be never used
        # # Optional peel-off in whitened domain (helps reduce overlap influence)
        # if self.cfg.enable_peel_off:
        #     Xw_res = Xw.copy()
        #     for i in range(n_mu):
        #         if len(spikes[i]) == 0:
        #             continue
        #         # peel_off expects channels x time; Xw_res is [Din, T] already
        #         Xw_res, _, _ = peel_off(
        #             Xw_res, spikes[i],
        #             win=self.cfg.peel_win,
        #             fsamp=fsamp
        #         )


        return spikes, scores
    
    def _lp_lq_sparsity(self, s_hat: torch.Tensor):
        """
        Temporal sparsity penalty: log10( (q/p) * ||s||_p / ||s||_q ), averaged over units.
        s_hat: [B, dlat]
        We compute norms over time within a window; aggregate across batch as mean.
        """
        # Sum across batch -> a time-aggregated view for this mini-batch
        # (treat batch as temporal slices)
        s_hat = torch.clamp(s_hat, min=0.0)  # already ReLU but be safe
        # Compute norms per-unit across batch
        # Avoid zero by eps to keep gradient stable
        lp = torch.pow(torch.sum(
            torch.pow(s_hat + self.sparsity_eps, self.sparsity_p), dim=0) 
            + self.sparsity_eps, 1.0 / self.sparsity_p
        )   # [dlat]
        lq = torch.pow(torch.sum(
            torch.pow(s_hat + self.sparsity_eps, self.sparsity_q), dim=0) 
            + self.sparsity_eps, 1.0 / self.sparsity_q
        )   # [dlat]
        ratio = (self.sparsity_q / self.sparsity_p) * (
            lp / (lq + self.sparsity_eps)
        )
        penalty = torch.log10(ratio + self.sparsity_eps).mean()

        return penalty
    
    def fit(self, sig: np.ndarray):
        """
        Fit the weights of the autoencoder given training data

        Args
        ----
            sig : np.ndarray 
                EMG data (n_channels, n_samples)
            fsamp: float 
                sampling frequency (Hz)


        """
        # Preprocess (extension + whitening) 
        Xe = self._extension(sig) # (n_features, n_samples)
        Xw = self._whitening(Xe)  # (n_features, n_samples)

        Xw_torch = self._to_torch(Xw)

        # Build and train autoencoder
        self._init_autoencoder(
            n_features=Xw.shape[0], n_emg_ch=sig.shape[0])
        self._train_autoencoder(Xw_torch.T)

    def fit_predict(
            self, 
            sig: np.ndarray, 
            fsamp: float
    ):
        """
        Args
        ----
            sig : np.ndarray 
                EMG data (n_channels, n_samples)
            fsamp: float 
                sampling frequency (Hz)

        Returns
        -------
            spikes : pd.DataFrame 
                Spike table (columns: onset, duration, sample, unit_id, description)
            sources : np.ndarray 
                Estimated latents / sources (n_components x n_samples)
            scores : dict of np.ndarray 
                Source trustworthiness scores ("sil" and "cov_isi")

        """
        # Preprocess (extension + whitening) 
        Xe = self._extension(sig) # (n_features, n_samples)
        Xw = self._whitening(Xe)  # (n_features, n_samples)

        Xw_torch = self._to_torch(Xw)

        # Build and train autoencoder
        self._init_autoencoder(
            n_features=Xw.shape[0], n_emg_ch=sig.shape[0])
        self._train_autoencoder(Xw_torch.T)

        # Predict latent sources for the given data
        with torch.no_grad():
            _, s_hat = self.autoencoder_(Xw_torch.T)

        # Convert the latent sources to numpy array (n_latents, n_samples)
        sources = s_hat.transpose(0, 1).cpu().numpy() 

        # Apply peak detection and extract quality scores
        spikes, scores = self._postprocess(sources, fsamp)

        # Convert dict of spikes to long-formated spike table 
        spikes = spike_dict_to_long_df(spikes)

        return spikes, sources, scores
    
    def predict(
            self, 
            sig: np.ndarray, 
            fsamp: float
    ):
        """
        Predict motor unit spikes based on the trained autoencoder
        model given some data. 

        Args
        ----
            sig : np.ndarray 
                EMG data (n_channels, n_samples)
            fsamp: float 
                sampling frequency (Hz)

        Returns
        -------
            spikes : pd.DataFrame 
                Spike table (columns: onset, duration, sample, unit_id, description)
            sources : np.ndarray 
                Estimated latents / sources (n_components x n_samples)
            scores : dict of np.ndarray 
                Source trustworthiness scores ("sil" and "cov_isi")

        """
        # Preprocess (extension + whitening) 
        Xe = self._extension(sig)
        Xw = self.white_ @ Xe 

        Xw_torch = self._to_torch(Xw)

        # Predict latent sources for the given data
        with torch.no_grad():
            _, s_hat = self.autoencoder_(Xw_torch.T)

        # Convert the latent sources to numpy array (n_latents, n_samples)
        sources = s_hat.transpose(0, 1).cpu().numpy() 

        # Apply peak detection and extract quality scores
        spikes, scores = self._postprocess(sources, fsamp)

        # Convert dict of spikes to long-formated spike table 
        spikes = spike_dict_to_long_df(spikes)

        return spikes, sources, scores
